function drift = d1_drift_calc(L_choice,constant, partially_constant, num_state_vars)
drift = constant ... 
    + sum(partially_constant...
          .* permute(repmat(L_choice, [ones(1,3), num_state_vars]),[1,4,2,3]), ...
          3);
end