function drift = d1_drift_calc(L_to_the_alpha_1,constant, partially_constant, dim)
drift = constant - squeeze(sum(partially_constant...
    .* repmat(reshape(L_to_the_alpha_1, [dim.len_Sigma, 1, dim.num_mkts, dim.num_networks]),...
    [1, dim.num_state_vars, 1, 1])...
    ,3));
end

 